### ISSUE TITLE
CustomMicrophone does not work on Windows

### ISSUE THREAD

**Issue by breandan** [OpenASR/idear#16]
CustomMicrophone does not work due to a [known issue](https://github.com/cmusphinx/sphinx4/issues/33) with CMUSphinx.

**Comment by alexeykudinkin** [comment]
Does that mean that we're un-recoverably broken on Windows. 
I mean, that `CustomMicrophone` doesn't diverge that much from `Microphone`.

**Comment by breandan** [comment]
It's not as much a problem with our implementation as `Microphone`. Whenever the user says "ok idea", an `IllegalStateException` gets thrown. CMUSphinx is working on [a patch](https://sourceforge.net/p/cmusphinx/bugs/412/).

**Comment by breandan** [comment]
I suppose the fix for this is to recompile CMUSphinx when the next version is released.

**Comment by jskye** [comment]
hi. is there a patch for this available @breandan ?

**Comment by breandan** [comment]
Hi @jskye, there is not yet a fix for Windows.

**Comment by jskye** [comment]
ok thanks for the reply. this only blocks the use of two LiveSpeechRecogniser's at once correct?

**Comment by breandan** [comment]
Yes, this issue should not affect most commands, but it will crash when you say, "okay google". I have not discovered a successful workaround.

**Comment by IgorJorobus** [comment]
Hi @breandan, I report same issue here. Any news on this?

**Comment by breandan** [comment]
We are planning to replace CMUSphinx with another ASR library, which should (in theory) fix this issue. Please follow #52 for updates.
