### ISSUE TITLE
Consider using J.A.R.V.I.S

### ISSUE THREAD

**Issue by breandan** [OpenASR/idear#20]
We could move the GSAPI code to use [J.A.R.V.I.S](https://github.com/lkuza2/java-speech-api). 

**Pros**
- Lightweight
- Well documented
- More functionality

**Cons**
- No unit tests
- Not maintained?
- Must be compiled

Thoughts? @alexeykudinkin @sweetybanana

**Comment by nalbion** [comment]
@breandan I've started working on this here - https://github.com/nalbion/java-speech-api/tree/feature/lex-recogniser

**Comment by nalbion** [comment]
https://github.com/lkuza2/java-speech-api/issues/83
