### ISSUE TITLE
Consider using Wit.ai.

### ISSUE THREAD

**Issue by mbait** [OpenASR/idear#22]
Hi there!

It's nice to see your project. Actually I had the same idea some time ago, but due to a lack of time it didn't go further. I used to work on CMU Sphinx, so feel free to ask questions about that as well as about speech recognition in general. I also worked in wit.ai (which has been acquired by Facebook) - a service that let's you define something similar to JSGF grammar that you currently use, but in a more flexible way. Of course you'd have to go online if you decide it.

At a glance the idea of what wit.ai does is a bit opaque, but let me quickly give an example. Suppose, you want to define action for creating a new class, so the system should be able to understand "create static class foo bar". This is not possible with grammar, because in this case you should define all possible names (like "foo" and "bar") in the grammar. Wit.ai let's you make a model that could recognize common part (create class) and its attributes (static, foo bar) and return recognition results in a structured way. I used to create a test model which you can find at https://wit.ai/mbait/vide. Let me know if you have questions.

Cheers!

**Comment by alexeykudinkin** [comment]
Hi @mbait! 

Wit.ai looks awesome!

Nevertheless it pulls us go online, which doesn't seem as a particular drawback, though impedes it as  a self-contained solution.

**Comment by breandan** [comment]
I agree. The idea is to use offline recognition wherever possible and only call a service when the user clearly intends to do so (ie. Google an error or exception). Privacy aside, I think it would be much more interesting to try and decode speech offline anyway. You're not going to learn anything by calling an API (although I'm sure it's a fine product).
