### ISSUE TITLE
The link to the command grammar is broken in IDEA

### ISSUE THREAD

**Issue by Error1000** [OpenASR/idear#38]
The link to the command grammar in the description of the plugin in IDEA is broken:
Here's where the link points to:
https://github.com/OpenASR/idear/blob/master/src/resources/com.jetbrains.idear/grammars/command.gram
That url dosen't exist anymore.

**Comment by breandan** [comment]
The link should point [here](https://github.com/OpenASR/idear/blob/master/src/main/resources/org.openasr.idear/grammars/command.gram). Will update, thanks for reporting.

**Comment by Error1000** [comment]
Thanks  for the link i'm going to close this issue now because you are goin to update the link in the idea description soon.
