### ISSUE TITLE
Failed to notify project evaluation listener - JAXBContext

### ISSUE THREAD

**Issue by nalbion** [OpenASR/idear#51]
```
$ ./gradlew runIde

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'idear'.
> Failed to notify project evaluation listener.
   > javax/xml/bind/JAXBContext

$ ./gradlew --version
------------------------------------------------------------
Gradle 4.9-20180613100740+0000
------------------------------------------------------------

Build time:   2018-06-13 10:07:40 UTC
Revision:     505792df79c2113d1f401761e352b713d2dc8785

Kotlin DSL:   0.18.2-SNAPSHOT
Kotlin:       1.2.41
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          10.0.1 ("Oracle Corporation" 10.0.1+10)
OS:           Mac OS X 10.13.5 x86_64
```

**Comment by breandan** [comment]
Are you using the latest master? We've updated to [Kotlin `1.2.50`](https://github.com/OpenASR/idear/blob/master/build.gradle.kts#L3) last week. Also, I think the IntelliJ Platform may specifically require [JDK 1.8](https://github.com/JetBrains/intellij-community#building-and-running-from-the-ide) to build.

**Comment by nalbion** [comment]
Stupid question: How do you upgrade Kotlin?  I've installed the latest version of IntelliJ Pro - it has Kotlin 1.2.50 and `build.gradle.kts` mentions kotlin 1.2.50, but `.gradlew --version` remains unchanged.

I'm also getting another error (on a Linux machine):

```
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find AceJump/lib/AceJump-3.5.0.jar (org.jetbrains.plugins:AceJump:3.5.0).
     Searched in the following locations:
         file:/home/nalbion/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/be099a2c25b1e63cae5d05f7f53b3e4fb9a9c551/ideaIC-LATEST-EAP-SNAPSHOT/plugins/AceJump/AceJump/lib/AceJump-3.5.0.jar
         file:/home/nalbion/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/plugins.jetbrains.com/AceJump-3.5.0/AceJump/lib/AceJump-3.5.0.jar
         file:/home/nalbion/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/LATEST-EAP-SNAPSHOT/c3a421e20746601f882c100d5f35be5e25627af0/ideaIC-LATEST-EAP-SNAPSHOT-sources.jar/AceJump/lib/AceJump-3.5.0-3.5.0.jar
```

**Comment by breandan** [comment]
Hmm, I was mistaken. The Kotlin version displayed by `./gradlew --version` is the Kotlin version used by the Gradle Kotlin DSL - not our Kotlin. You shouldn’t need to upgrade anything else - `./gradlew runIde` will do everything for you. However, you may need to downgrade to JDK 1.8, that’s the only dependency required by gradlew and it is shared by the IntelliJ Platform.

**Comment by nalbion** [comment]
https://travis-ci.com/OpenASR/idear/jobs/130280990

**Comment by nalbion** [comment]
I've pushed a Docker file which can be used to reproduce the issue with AceJump - perhaps the jar needs to be added to the Docker image.

**Comment by breandan** [comment]
Can you `ping https://plugins.jetbrains.com/` from the build machine? This artifact is downloaded from the JetBrains Plugin Repository by the `plugins` attribute of the [gradle-intellij-plugin](https://github.com/JetBrains/gradle-intellij-plugin#setup-dsl).

**Comment by breandan** [comment]
I’m not sure why it’s trying to fetch AceJump 3.5.0, since we’re using an older version: https://github.com/OpenASR/idear/blob/ab7751343e3f7a4c3caf5f0a2e9f9a3ba4d40fdb/build.gradle.kts#L9

**Comment by nalbion** [comment]
I tried 3.3.5 and 3.5.0 - neither work. TravisCI tried to download 3.3.5 and failed

**Comment by nalbion** [comment]
@Brendan can you pull and run `make docker`?

**Comment by zolotov** [comment]
@nalbion so it works locally and doesn't work in docker and on the travis? What the OS you use locally? If not Linux, then it sounds like case-sensitivity problem. ID of AceJump plugin is definitely `AceJump`, not `acejump`

**Comment by breandan** [comment]
Weird, this definitely worked before. Thanks for your help @zolotov!

**Comment by nalbion** [comment]
Thanks @zolotov and @breandan
