### ISSUE TITLE
Replace CMUSphinx

### ISSUE THREAD

**Issue by breandan** [OpenASR/idear#52]
Integrate [`mozilla/deepspeech`](https://github.com/mozilla/deepspeech) ~once real-time streaming inference is implemented~. Depends on mozilla/deepspeech#847, mozilla/deepspeech#1275

edit: It appears that DeepSpeech now supports a [streaming API with Java bindings](https://deepspeech.readthedocs.io/en/v0.7.0/Java-API.html), but only for Android. [JVM bindings](https://github.com/mozilla/DeepSpeech/issues/2129) were unfortunately [rejected](https://github.com/mozilla/DeepSpeech/pull/2166#issuecomment-500955964).

**Comment by nalbion** [comment]
I've made a start on this:
https://github.com/OpenASR/idear/commit/a945ad405eb7e5a69d5f3abf0c306966d93372d2

**Comment by breandan** [comment]
@kenarsa Can you clarify what features the Picovoice license supports for open source projects like ours? In particular, it looks like [Cheetah](https://github.com/Picovoice/cheetah#cheetah) has some restrictions around using custom vocabularies:

> Allows adding new words and adapting to different contexts (Available only under the commercial license).

Are there plans to allow open source projects to train their own models or deploy models trained via the Picovoice console? Any guidance you can provide for our use case (small to medium vocabulary custom language models) would be highly appreciated. Thanks!

**Comment by nalbion** [comment]
Actually @kenarsa, I am a bit concerned about the limitations of Picovoice: 

> 5 contexts, each with a limit of 50 unique words and 150 total words, 5 intents, and 5 slots.

https://picovoice.ai/console/

IntelliJ has a large number of actions that could potentially be invoked by speech-to-intent:

- [ExternalSystemActions](https://upsource.jetbrains.com/idea-ce/file/idea-ce-1d111593d9e5208b6783f381b507e34866587ec8/platform/platform-resources/src/idea/ExternalSystemActions.xml)
- [LangActions](https://upsource.jetbrains.com/idea-ce/file/idea-ce-1d111593d9e5208b6783f381b507e34866587ec8/platform/platform-resources/src/idea/LangActions.xml)
- [PlatformActions](https://upsource.jetbrains.com/idea-ce/file/idea-ce-1d111593d9e5208b6783f381b507e34866587ec8/platform/platform-resources/src/idea/PlatformActions.xml)
- [VcsActions](https://upsource.jetbrains.com/idea-ce/file/idea-ce-1d111593d9e5208b6783f381b507e34866587ec8/platform/platform-resources/src/idea/VcsActions.xml)

**Comment by kenarsa** [comment]
the license terms are set and we don't have plans to change them. For console you can look into the terms here: https://picovoice.ai/docs/terms-of-use/ and each product Github repo explains the license and limitations. Our offerings are geared towards mid-large scale enterprises. I hope it helps. Cheers!

**Comment by breandan** [comment]
@kenarsa Thank you for your reply. It seems like Picovoice primarily targets enterprise IoT and edge computing, where case these license limitations make sense. Understand why these are necessary, but the [operating system restrictions](https://github.com/Picovoice/leopard#leopard) and lack of [grammar](https://news.ycombinator.com/item?id=18202669) support for noncommerical applications are not really compatible with our project's goals.

@nalbion It might make more sense to focus our efforts on improving DeepSpeech for Java, which already offers [Android bindings](https://deepspeech.readthedocs.io/en/v0.7.0/Java-API.html) and seems to be a better fit for desktop applications. You might want to check out @GommeAntiLegit's [Java library](https://github.com/GommeAntiLegit/DeepSpeech-Java-Bindings/tree/master/libdeepspeech), or see if there is a way to work with mozilla/DeepSpeech#2166 to upstream an API for other JVM users.

**Comment by nshmyrev** [comment]
@breandan we have word lists you can simply use to improve accuracy like [here in python](https://github.com/alphacep/vosk-api/blob/master/python/example/test_words.py) . I might make you jars if you need them too, let me know the platforms you need to support.

**Comment by breandan** [comment]
Thanks, it looks like a promising replacement. Our goal is to generate contextual grammars for various IDE menus. This should be possible by listening for keywords, but it would be nice to support custom language models, using an approach like #6.

>  I might make you jars if you need them too, let me know the platforms you need to support.

That would be great. I was just creating a ticket here: alphacep/vosk-api#95. I guess Linux_x64 and whatever @nalbion uses for development would be a good place to start.

**Comment by nalbion** [comment]
I'm using Windows x64

**Comment by nalbion** [comment]
@breandan how would you provide the `.so`/`.dll` libraries with the plugin?

**Comment by breandan** [comment]
The way I’ve seen this done before is to bundle the `.dll`/`.dylib`/`.so` for all platforms in the same JAR, then use that JAR as a plugin dependency. I think [this project](https://github.com/bytedeco/javacpp-presets) does that, I can run it the same native library from a JAR on multiple platforms, as long as it matches one of the compiler targets.

**Comment by breandan** [comment]
If you’re compiling manually, you may need to determine the correct binary to use based on a syscall, I’m not actually sure how that works in JavaCPP.

**Comment by breandan** [comment]
[Z3-TurnKey](https://github.com/tudo-aqua/z3-turnkey#how) is a great example of how to build a single JAR with multiplatform native libraries bundled inside. If you inspect [the JAR](https://search.maven.org/remotecontent?filepath=io/github/tudo-aqua/z3-turnkey/4.8.7.1/z3-turnkey-4.8.7.1.jar) it contains prebuilt native binaries for OSX/Linux/Windows. [Here](https://github.com/tudo-aqua/z3-turnkey/blob/eb2ae31ad0390c1175e9a876b977d688e673ea2d/src/main/java/com/microsoft/z3/Z3Loader.java#L55) is the logic for dispatching to the correct library at runtime. The [Gradle build logic](https://github.com/tudo-aqua/z3-turnkey/blob/eb2ae31ad0390c1175e9a876b977d688e673ea2d/build.gradle.kts#L251) may also be helpful.

**Comment by daanzu** [comment]
I just saw your comment on Hacker News, and [replied](https://news.ycombinator.com/item?id=23507829) with a mention of [my project](https://github.com/daanzu/kaldi-active-grammar), which may be useful to yours. Let me know if you want to work together!

**Comment by breandan** [comment]
@daanzu Thank you for reaching out! Your grammar swapping functionality does indeed look like what we were originally looking for #6. Since our tool is currently JVM based, we'll need a way to distribute a single artifact without asking users to install other dependencies (Python, Kaldi, etc.) Do you have any plans to publish a standalone REST/RPC server or external language bindings?

**Comment by daanzu** [comment]
@breandan Hmm, the current version of KaldiAG has a large Python component (the rest being C++, along with Kaldi itself). Python speeds development, and the `pip` infrastructure makes distributing the binaries (for all major platforms) easy. Other language bindings are still possible, but would involve a fair bit of implementation and maintenance work. However, I have been considering whether to try to move more of the implementation into C++.

On the other hand, adding a REST/RPC server and interface to the current Python package shouldn't be too hard. I don't really know much of anything about how JVM distribution works nowadays, especially regarding binaries. How would that work?

**Comment by breandan** [comment]
>I don't really know much of anything about how JVM distribution works nowadays, especially regarding binaries. How would that work?

Ideally, KaldiAG would publish a headless, batteries-included executable for Windows OSX and Linux, and we would include all three and just launch the correct one based on the OS. There would need to be some way to swap grammars, but otherwise it shouldn't be too difficult.

The alternative is to publish native libraries which we could call into via JNI. This is probably more difficult to implement as most of the code is written in Python, but should be doable.
